-- Fit & Glow Club database snapshot.
-- Apply migrations in supabase/migrations in timestamp order.
-- Current foundation migration:
-- supabase/migrations/20260714220000_initial_project_foundation.sql
-- Workout module migration:
-- supabase/migrations/20260714223000_workout_module.sql
